//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace myTracker
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet Model1Container à l'aide de la chaîne de connexion trouvée dans la section 'Model1Container' du fichier de configuration d'application.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Model1Container.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Model1Container.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<MyCards> MyCards
        {
            get
            {
                if ((_MyCards == null))
                {
                    _MyCards = base.CreateObjectSet<MyCards>("MyCards");
                }
                return _MyCards;
            }
        }
        private ObjectSet<MyCards> _MyCards;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet MyCards. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMyCards(MyCards myCards)
        {
            base.AddObject("MyCards", myCards);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="MyCards")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MyCards : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet MyCards.
        /// </summary>
        /// <param name="handId">Valeur initiale de la propriété HandId.</param>
        /// <param name="card1">Valeur initiale de la propriété Card1.</param>
        /// <param name="card2">Valeur initiale de la propriété Card2.</param>
        public static MyCards CreateMyCards(global::System.Int32 handId, global::System.String card1, global::System.String card2)
        {
            MyCards myCards = new MyCards();
            myCards.HandId = handId;
            myCards.Card1 = card1;
            myCards.Card2 = card2;
            return myCards;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HandId
        {
            get
            {
                return _HandId;
            }
            set
            {
                if (_HandId != value)
                {
                    OnHandIdChanging(value);
                    ReportPropertyChanging("HandId");
                    _HandId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HandId");
                    OnHandIdChanged();
                }
            }
        }
        private global::System.Int32 _HandId;
        partial void OnHandIdChanging(global::System.Int32 value);
        partial void OnHandIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Card1
        {
            get
            {
                return _Card1;
            }
            set
            {
                OnCard1Changing(value);
                ReportPropertyChanging("Card1");
                _Card1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Card1");
                OnCard1Changed();
            }
        }
        private global::System.String _Card1;
        partial void OnCard1Changing(global::System.String value);
        partial void OnCard1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Card2
        {
            get
            {
                return _Card2;
            }
            set
            {
                OnCard2Changing(value);
                ReportPropertyChanging("Card2");
                _Card2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Card2");
                OnCard2Changed();
            }
        }
        private global::System.String _Card2;
        partial void OnCard2Changing(global::System.String value);
        partial void OnCard2Changed();

        #endregion
    
    }

    #endregion
    
}
